### ISSUE TITLE
ModuleNotFoundError: No module named 'lama'

### ISSUE THREAD

**Issue by sanjibnarzary** [facebookresearch/LAMA#20]
I got the following error while executing `./download_dataset.sh` for the first time. The same problem appears when I tried to execute the same script again.

```
Building common vocab                        
Traceback (most recent call last):           
  File "lama/vocab_intersection.py", line 7, 
in <module>                                  
    from lama.modules import build_model_by_n
ame                                          
ModuleNotFoundError: No module named 'lama'
```

**Comment by fabiopetroni** [comment]
in Troubleshooting
`export PYTHONPATH=.`

**Comment by sanjibnarzary** [comment]
Nothing changes. Here is the complete output log
`./download_models.sh`
```
lowercase models
OpenAI GPT
BERT BASE LOWERCASED
BERT LARGE LOWERCASED
cased models
Transformer XL
ELMO ORIGINAL 5.5B
ELMO ORIGINAL
BERT BASE CASED
BERT LARGE CASED
Building common vocab
Traceback (most recent call last):
  File "lama/vocab_intersection.py", line 7, in <module>
    from lama.modules import build_model_by_name
ModuleNotFoundError: No module named 'lama.modules'
```

**Comment by fabiopetroni** [comment]
thanks
